
rootProject.name = "tilapia"
include("tilapia-common")
include("tilapia-lobby")
include("tilapia-api")
include("tilapia-core")
include("fan87-plugin-dev-kit")
include("tilapia-spigot-common")
include("tilapia-game-extension")
include("tilapia-command")
include("tilapia-fleetwars")
include("tilapia-language")
include("tilapia-multiworld")
include("tilapia-util-commands")
include("tilapia-sandbox")
include("tilapia-backend")
include("tilapia-communication")
include("tilapia-proxy-api")
include("tilapia-proxy-core")
include("tilapia-proxy-util-commands")
