# MySQL / MariaDB

---
apiVersion: v1
kind: Service
metadata:
  name: tilapia-mysql
  labels:
    app: game-central
spec:
  ports:
    - port: 3306
  selector:
    app: game-central-mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilapia-mysql
  labels:
    app: game-central
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: game-central-mariadb
  template:
    metadata:
      labels:
        app: game-central-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-persistent-storage
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: tilapia-mysql-volume-claim
      restartPolicy: Always


# Game Central

---
apiVersion: v1
kind: Service
metadata:
  name: tilapia-game-central
  labels:
    app: game-central
spec:
  ports:
    - port: 8080
  selector:
    app: game-central
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilapia-game-central
  labels:
    app: game-central
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: game-central
  template:
    metadata:
      labels:
        app: game-central
    spec:
      containers:
        - name: game-central
          image: docker.tilapiamc.net:443/repository/docker/tilapia-game-central:snapshot
          ports:
            - containerPort: 8080
          tty: true
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: password
            - name: DATABASE_USER
              value: root
            - name: DATABASE_URL
              value: jdbc:mysql://tilapia-mysql:3306
            - name: HOST
              value: 0.0.0.0
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: game-central-pass
                  key: api-key

      restartPolicy: Always


# Proxy
---
apiVersion: v1
kind: Service
metadata:
  name: tilapia-proxy
  labels:
    app: minecraft-proxy
spec:
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  selector:
    app: minecraft-proxy
  type: LoadBalancer
  loadBalancerIP: 192.168.1.105
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilapia-proxy
  labels:
    app: minecraft-proxy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-proxy
  template:
    metadata:
      labels:
        app: minecraft-proxy
    spec:
      containers:
        - name: minecraft-proxy
          image: docker.tilapiamc.net:443/repository/docker/tilapia-proxy:snapshot
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
          tty: true
          stdin: true
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: game-central-pass
                  key: api-key
            - name: BACKEND_HOST
              value: tilapia-game-central
            - name: DATABASE_HOST
              value: tilapia-mysql

      restartPolicy: Always

