
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-central-local-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /storage/game-central
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - archlinux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tilapia-mysql-volume-claim
  labels:
    app: game-central
spec:
  storageClassName: 'local-storage'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi