apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tilapia-01-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.105-192.168.1.105
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: snapshot-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - tilapia-01-pool